skip_local_validator = true

[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
argus = "9zJEWrk47z1ACT3ySMwzmUrMsQzFC8afBSFcsCzsz3rx"
vesta_core = "gaMq6BpH1aqC8ZCYtAxwZBjTa9AnfdWvYwURG6L4LDz"

[programs.localnet]
argus = "9zJEWrk47z1ACT3ySMwzmUrMsQzFC8afBSFcsCzsz3rx"
vesta_core = "gaMq6BpH1aqC8ZCYtAxwZBjTa9AnfdWvYwURG6L4LDz"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
